/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_osu_cse_ops_UDS */

#ifndef _Included_edu_osu_cse_ops_UDS
#define _Included_edu_osu_cse_ops_UDS
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_osu_cse_ops_UDS
 * Method:    add
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_edu_osu_cse_ops_UDS_add
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     edu_osu_cse_ops_UDS
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_osu_cse_ops_UDS_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
